trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build and FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build and SecondJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeply
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob

